spring:
  datasource:
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5434/postgres
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true